question_data = [
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "&quot;Typewriter&quot; is the longest word that can be typed using only the first row on a QWERTY keyboard.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                  "question": "The vapor produced by e-cigarettes is actually water.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                  "question": "Cucumbers are usually more than 90% water.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                  "question": "You are allowed to sell your soul on eBay.", "correct_answer": "False",
                                  "incorrect_answers": ["True"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                  "question": "The term &quot;Spam&quot; came before the food product &quot;Spam&quot;.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                  "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                  "question": "The French word for &quot;glass&quot; is &quot;glace&quot;.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                  "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                  "question": "The scientific name for the Southern Lights is Aurora Australis?",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                  "question": "The pickled gherkin was first added to hamburgers because a US health law required all fast-food to include a source of Vitamin C.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]}]
